[theme]
primaryColor="#4CAF50"
backgroundColor="#000000"
secondaryBackgroundColor="#1a1a1a"
textColor="#ffffff"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 500

[browser]
gatherUsageStats = false